# Generated by Django 2.2.6 on 2020-02-23 00:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report_gen', '0002_upload_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
