version: '3'
services:
    backend:
        image: jesusrmendoza/odasbackend:latest
        ports:
            - "8080:8080"
        volumes:
            - ./backend:/odas/backend
        command: bash -c "cd odas/backend/odas_backend/ && python manage.py runserver 0.0.0.0:8080"
    frontend:
        image: node:12
        ports:
            - "3000:3000"
        volumes:
            - ./odas-ui:/odas/odas-ui
        command: bash -c "cd odas/odas-ui && npm start"
        depends_on:
            - backend
