version: '3'
services:
    backend:
        image: jesusrmendoza/odasbackend:latest
        ports:
            - "8000:8000"
        volumes:
            - ./:/odas
        command: bash -c "cd odas/backend/odas_backend/ && python manage.py runserver 0.0.0.0:8000"
