# Generated by Django 2.2.6 on 2019-10-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('mission_description', models.CharField(max_length=512)),
                ('year_lauched', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
