# Generated by Django 2.2.6 on 2019-10-24 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odas', '0002_auto_20191020_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='collectable',
        ),
        migrations.AddField(
            model_name='measurement',
            name='component',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='odas.Component'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Collectable',
        ),
        migrations.AddField(
            model_name='measurement',
            name='units',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='odas.Units'),
            preserve_default=False,
        ),
    ]
