# Generated by Django 2.2.6 on 2019-10-24 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odas', '0003_auto_20191024_0741'),
        ('odas', '0002_upload'),
    ]

    operations = [
    ]
