# Generated by Django 2.2.6 on 2019-11-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odas', '0005_auto_20191024_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timesave', models.DateTimeField(auto_now_add=True)),
                ('filesize', models.FloatField()),
                ('filename', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('filename', models.CharField(max_length=30)),
                ('filesize', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
