# Generated by Django 2.2.6 on 2019-11-18 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odas', '0005_auto_20191024_2148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
