# Generated by Django 2.2.6 on 2020-02-10 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odas', '0007_satellite_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.CharField(max_length=512)),
                ('priority', models.IntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odas.Component')),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odas.Satellite')),
                ('units', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odas.Units')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odas.Measurement')),
            ],
        ),
    ]
