# Generated by Django 2.2.6 on 2019-11-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='link',
            field=models.CharField(db_index=True, max_length=12, unique=True),
        ),
    ]
